### ISSUE TITLE
syncthing and discosrv on the same machine

### ISSUE THREAD

**Issue by adi-dev** [syncthing/discosrv#11]
I've noticed that when I run discosrv on the same machine the syncthing is running it doesn't present this machine on the network (or it does but with local ip address so syncthing cannot reach it from wan, my guess). If I point syncthing to this machine ip it links with no problem. If I set to "dynamic" my laptops syncthing can only reach this machine when I'm within LAN.

**Comment by calmh** [comment]
The discovery server uses the source address of the announcement packets as the device address. This is as designed.

**Comment by calmh** [comment]
But if your external devices know the IP of and can reach the discovery server, they can reach the syncthing instance you have on the same machine as well...

**Comment by AudriusButkevicius** [comment]
Subject the protocol port is forwarded.

**Comment by adi-dev** [comment]
It's okay if broadband modem can handle addressing local machine with external ip. I've noticed on mine it struggles: sometimes it doesn't forward traffic (local -> wan -> local) and most the time the link is very slow, almost like the data goes out somewhere and then comes back so instead of fast syncing it behaves like syncing using server outside lan.
