### ISSUE TITLE
Unable to connect from build 1313

### ISSUE THREAD

**Issue by Superman1001** [syncthing/discosrv#16]
I was updating my private discover, based on windows server x64.
I found this problem: from build Build #1313 (Aug 20, 2015 12:28:41 PM) discover starts and stays in listening, but the clients (in my case one android and one debian) are unable to connect to the discover server. With older build, 1309 and previous, my clients are able to connect to discover server with no problems.
I tried both x64 and x86 versions taken from here:
http://build.syncthing.net/job/discosrv/lastSuccessfulBuild/artifact/

**Comment by calmh** [comment]
The current `master` build is for the v0.12 branch. For v0.11 devices there is no newer build than the one you had; you should continue using that for v0.11 devices.
