### ISSUE TITLE
restrict access to discosrv

### ISSUE THREAD

**Issue by readyblue** [syncthing/discosrv#17]
Having a private discosrv is nice, but without some sort of access list for nodes it may seems little useless, or only as some redundancy to main discosrv.

Can you please add some access list feature to this amazing project?

**Comment by calmh** [comment]
I think that would be better handled by a firewall, on system or otherwise?

**Comment by readyblue** [comment]
how possibly I can restrict access of some node by firewall, when I do not have its IP address?

**Comment by AudriusButkevicius** [comment]
You could also run it in a VPN.

**Comment by readyblue** [comment]
let us say, I would like to start discosrv on some small device like raspberry PI, yet I do not want to work for any other device, but : device1, device2 and device3. Now this is not possible to restrict the access for device4 once it will know on what IP:port the discosrv is running.

**Comment by readyblue** [comment]
@AudriusButkevicius yes, VPN might work for this purpose.

**Comment by calmh** [comment]
Ah, how were you imagining the access list would work, and what problem would it solve?

**Comment by readyblue** [comment]
It work like: here is the list of devices which may discover other devices. others devices (not in the list) may simply not discover anything. it may increase the security and possibly decrease the need for system resources and size of database.

**Comment by calmh** [comment]
A device does not identify itself when asking for the address of another device. So there is no possibility to limit answers to a know set of devices.

**Comment by readyblue** [comment]
I see, thanks @calmh for clarifying this, also thanks @AudriusButkevicius as VPN might just work for this
