### ISSUE TITLE
Darwin AMD64 not running on Mac 10.7

### ISSUE THREAD

**Issue by lantrix** [syncthing/discosrv#18]
Is there a minimum OS version for the `Darwin` build? I get illegal instruction trying to run it.

    server:~ root# ls -l /usr/local/bin/discosrv       
    -rwxr-xr-x+ 1 user  staff  10065044 Sep  3 05:01 /usr/local/bin/discosrv
    server:~ root# /usr/local/bin/discosrv
    Illegal instruction: 4

**Comment by calmh** [comment]
The binaries are 10.8+, yes, sorry. You can compile them yourself for 10.7 though.

**Comment by lantrix** [comment]
I've rebuilt it from source and that works; however I'm not sure if there is still an OS version minimum on the Darwin binaries supplied.
