### ISSUE TITLE
Securing updates against forgery and replay

### ISSUE THREAD

**Issue by davidstrauss** [syncthing/discosrv#2]
After sleeping on issue #1, I gave this part of the problem some more thought, especially in terms of limiting complexity and reliance on external authorities.

If a client generated an S/MIME block (signing only, no encryption) containing its address information and sent that up to the server, two things could happen:

 1. Forged updates to the discovery server would be discarded because the server would use the hash of the certificate used in signing to find the Node ID for storage of the information.
 1. The discovery server could send that S/MIME block, fully intact, down to clients as the discovery response, allowing clients to validate the data and discard forged responses.

If the date is included in the signed data, a replay attack with expired data would also not be possible, as neither server nor client would permit an older update to replace newer data.

**Comment by AudriusButkevicius** [comment]
This has been dealt with in the new version which uses HTTP and client side certificate checking.
