### ISSUE TITLE
discosrv fails to build on Debian Jessie / bannapi /ARM

### ISSUE THREAD

**Issue by iggs0** [syncthing/discosrv#20]
Trying to build discosr for the banana pi I receive following error:
```$ go get github.com/syncthing/discosrv
# github.com/cznic/zappy
In file included from go/src/github.com/cznic/zappy/decode_cgo.go:15:0:
/usr/lib/gcc/arm-linux-gnueabihf/4.9/include/stdint.h:9:26: fatal error: stdint.h: No such file or directory
 # include_next <stdint.h>
                          ^
compilation terminated.``` 
Any hint which dependency is missing. Which package (source package) is needed ?

**Comment by AudriusButkevicius** [comment]
Its the standard library headers, but you should use the build script provided which builds a go version, without any C dependencies.

**Comment by iggs0** [comment]
Sorry no luck with any std headers yet. What do you mean by build script. The Instruction I saw only mentioned  go get github.com/syncthing/discosrv

**Comment by AudriusButkevicius** [comment]
Just run `./build.sh`

**Comment by AudriusButkevicius** [comment]
Or add `-tags purego` to your go get

**Comment by iggs0** [comment]
o.k. found ./build.sh but ended with some runtime message.
The  go get -tags purego github.com/syncthing/discosrv did it.

Thanks - super fast service
