### ISSUE TITLE
broadcast: Self-lookup returned: []

### ISSUE THREAD

**Issue by iggs0** [syncthing/discosrv#21]
Installed discosrv on serveral maschines from latest build and building myself.
Command line is
discosrv -listen="192.168.xx.20:22027"

On the client I receive  
discover udp4://192.168.73.20:22027: broadcast: Self-lookup returned: []

The client shows Global Discovery 	0/1 
How can I debug discosrv ?

**Comment by AudriusButkevicius** [comment]
The latest build is for the upcoming 0.12 release, and not compatible with 0.11, use the 'standalone' release.

**Comment by iggs0** [comment]
.... you are so fast - amazing - :-) what do you mean with standalone release ?

**Comment by iggs0** [comment]
found it - https://github.com/syncthing/discosrv/releases
