### ISSUE TITLE
Documentation seems to be out of sync

### ISSUE THREAD

**Issue by monochromec** [syncthing/discosrv#24]
The documentation (http://docs.syncthing.net/users/discosrv.html) seems to out of sync with current version of source code (0.12.1). For example, by default discosrv seems to be listening on a TCP6 port instead of UDP4, even when specifying the port explicitly with "-listen". As a result, setting up your own discovery server is tricky when relying on the documentation alone instead of looking at the source code. 

A time line for the update of the documentation would be appreciated if possible.

**Comment by AudriusButkevicius** [comment]
0.12 is not released yet, hence the old docs.
