### ISSUE TITLE
Update discosrv image for v0.12 on Docker Hub

### ISSUE THREAD

**Issue by p1rox** [syncthing/discosrv#26]
Everything is in the title.

**Comment by AudriusButkevicius** [comment]
We don't run it via docker, so it was contributed by some third party.

**Comment by calmh** [comment]
Actually I think I built it, but it should probably be discontinued as we don't use it any more.

**Comment by calmh** [comment]
Or maybe not. https://forum.syncthing.net/t/discovery-docker/6034

(moving discussion there to keep things in one place)

**Comment by AudriusButkevicius** [comment]
Let's close?

**Comment by calmh** [comment]
Leaving open for visibility as it came up multiple times on just the release day. :)
