### ISSUE TITLE
Failed to load X509 key pair

### ISSUE THREAD

**Issue by Novaal** [syncthing/discosrv#27]
Hi,
i tried to install the discosrv on my server following http://docs.syncthing.net/users/discosrv.html

when i try to run discoserv as root from /usr/local/bin via 
> sudo discosrv -listen=":22026"

i get the error 
>Failed to load X509 key pair: open cert.pem: no such file or directory

Should i generate a extra cert/keypair or should i use a trusted cert?

folder /var/discosrv is generated and root has 755 access.

System:
Ubuntu 14.04.3 LTS

I tried the 12.1 Release and the latest build #1520

Thanks for your help

**Comment by calmh** [comment]
Hi,

Please see the new updated docs at http://docs.syncthing.net/users/discosrv.html

Thanks!
