### ISSUE TITLE
DiscoSrv issue

### ISSUE THREAD

**Issue by AlroneRhyn** [syncthing/discosrv#28]
Hi guys,

I'm heading into a sad issue : i can't get the discosrv ID at startup nor till it's running. I'm using a selfsigned CA. 
This happend on the arm version 0.12 on a raspberry PI 2. Is there a way to get it while it's running ? Or to force displaying it a startup ?

Thx a lot ! F***** Great software.

**Comment by AudriusButkevicius** [comment]
I don't understand the question. The ID is printed as it starts

**Comment by AlroneRhyn** [comment]
That's it : no it's not ;) Here is my issue

**Comment by calmh** [comment]
It's fixes in the code, but not released. I'll make a new release with this in it.

**Comment by AlroneRhyn** [comment]
Working ! Joie !

Thx a lot !
