### ISSUE TITLE
db-dsn incorrect example in Usage

### ISSUE THREAD

**Issue by CompuRoot** [syncthing/discosrv#29]
In the section of "Usage" there is example how to set up database in file:

    $discosrv -db-dsn="file://var/run/discosrv.db" 

This example prevent *discosrv* to start and issue warning message: **"Setup: open var/discosrv/db/discosrv.db: no such file or directory"**

Correct option should be issued as:

     $discosrv -db-dsn="file:///var/run/discosrv.db" 

with one more extra slash after *file://*

**Comment by calmh** [comment]
Thanks!
