### ISSUE TITLE
-stats-file option non-working

### ISSUE THREAD

**Issue by xamindar** [syncthing/discosrv#34]
When discosrv is launched with the -stats-file option, a file is not created. The output becomes this:
>$ ./discosrv -stats-file stats.log
>Server device ID is QAGANLY-GYB7C3L-RAFQXA5-F2KYCYJ-UTFXPGQ-UEDGAHG-3C6A5JD-6T6LYQY
>Stats: 0.00 announces/s, 0.00 queries/s, 0.00 answers/s, 0.00 errors/s
>stats query: 1:17 invalid expression COUNT(*)
>Database: 0 devices, 0 addresses, 0 relays
>Stats: 0.00 announces/s, 0.00 queries/s, 0.00 answers/s, 0.00 errors/s
>stats query: 1:17 invalid expression COUNT(*)

**Comment by canton7** [comment]
Looking at the source, it looks like it will both print stats and writing them to a file when `-stats-file` is given.

It also looks like it creates the stats file in the CWD - have you make sure you're looking for it in the right place? Have you tried specifying an absolute path?

**Comment by calmh** [comment]
The problem is that the ql backend doesn't like the count() query
