### ISSUE TITLE
Defer fd.Close() in stats.go?

### ISSUE THREAD

**Issue by kc1212** [syncthing/discosrv#37]
I was just browsing the source code and saw this: https://github.com/syncthing/discosrv/blob/master/stats.go#L131

Wouldn't it be better to do something like this right after `fd.OpenFile` succeeds?
```
	defer func() {
		err = fd.Close()
		if err != nil {
			log.Println("stats file:", err)
		}
	}
```

**Comment by AudriusButkevicius** [comment]
Probably, but I don't think we leak a fd as it gets closed then gc picks it up.

**Comment by calmh** [comment]
Indeed, but we shouldn't have code paths without explicit close in them so that should be fixed.
