### ISSUE TITLE
Official Release with v13 Support

### ISSUE THREAD

**Issue by Atera** [syncthing/discosrv#43]
Per AudriusButkevicius's suggestion, I am opening this issue as a reminder that Syncthing v0.13 and v0.13.1 have been released, but that there is not yet an official release for discosrv that is compatible with the new global discovery protocol these two use. It may be a good idea to provide an official release soon for those wishing to upgrade their setups entirely to the v13 protocols without having to build their own discosrv.

**Comment by calmh** [comment]
Thanks, fixed! :)
