### ISSUE TITLE
Document new API versioning path "/v2/"

### ISSUE THREAD

**Issue by acmodeu** [syncthing/discosrv#44]
Trying to set own discovery server...
1. Downloaded and unpacked discosrv-windows-amd64.zip.
2. Opened 8443 port on firewall and NATed it to the server host.
3. Generated certificates with `syncthing -generate="c:\discosrv-windows-amd64"`.
4. Opened command prompt and started server in debug mode `discosrv.exe -debug`.
5. Got `Server device ID is XXXXXXX-...`.
6. Pasted `https://ip:port/v2?id=XXXXXXX-...` to the Global Discovery Servers address string in 2 clients (version 0.13.1).
7. Got `301 moved permanently` when hovering mouse on discovery statistics in the clients and periodic message `bad device param` in the console.

**Comment by calmh** [comment]
For the 301, add a slash after v2 I think. For the other, not sure but double check the device id.

**Comment by acmodeu** [comment]
Yes, finally! That did all the magic! Thank you. I think you should mention this slash in [the annotation](https://github.com/syncthing/discosrv/releases) to the release.

**Comment by AudriusButkevicius** [comment]
Can this now be closed, given the docs are there (somewhat)?

**Comment by calmh** [comment]
Docs in the docs repo, now.
