### ISSUE TITLE
Accept domain names in announced addresses

### ISSUE THREAD

**Issue by majedev** [syncthing/discosrv#46]
I've been trying to configure syncthing to use FQDN for a private relay server, but it didn't work unless I used relay server's public IP address. Apparently, the current implementation [only accepts IP addresses](https://github.com/syncthing/discosrv/blob/master/querysrv.go#L332) in the announce POST request. If domain names were sent by the client, they will be replaced by client's IP address.

**Comment by AudriusButkevicius** [comment]
I am sure this is not intended.

**Comment by majedev** [comment]
Fixed in #48
