### ISSUE TITLE
CLI utility for doing lookups externally

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/discosrv#6]
Because reading STTRACE=discovery hex dumps is sad.

**Comment by calmh** [comment]
(and announcements?)

**Comment by AudriusButkevicius** [comment]
But this makes it easier to DoS if we make a tool available ;)

**Comment by calmh** [comment]
Isn't this stfinddevice then?

**Comment by AudriusButkevicius** [comment]
This is, I am just waiting for your counter-comment to my comment, whether or not you want the other utility before closing this.

**Comment by calmh** [comment]
Nah, forget that.
