### ISSUE TITLE
Images for wiki

### ISSUE THREAD

**Issue by Spellshaper** [syncthing/discosrv#9]
Figured I'd help out with the documentation as per https://github.com/syncthing/syncthing/issues/1624.
I don't use git, so I'll use the issues features for uploading images for the wiki.
![discosrv_guide1](https://cloud.githubusercontent.com/assets/10774151/7230925/16645aa4-e772-11e4-8df6-f0af9d9ce8b2.png)

**Comment by calmh** [comment]
:D

**Comment by calmh** [comment]
This is awesome, by the way. Thanks!

**Comment by Spellshaper** [comment]
Whatever helps. :)
Also, if you have suggestions for more docs that can be cobbled together by a non-programmer - I can't promise too much, but I'll try to devote some time to it.
